//! Generates the `STR_*` key constants from the translation source.
//!
//! Done here rather than by `scripts/gen_i18n.py` so that `cargo build`,
//! `cargo test` and `cargo clippy` work on a fresh clone with no PlatformIO
//! run first. The Python generator still owns the C++ side and the actual
//! translated text; this only mirrors the key names, which is all Rust needs —
//! `tr!` looks the text up at run time.

use std::path::Path;
use std::{env, fs};

/// Where the keys come from. English is the reference; other languages fall
/// back to it, so it always has every key.
const SOURCE: &str = "../../lib/I18n/translations/english.yaml";

fn main() {
    // Only re-run when the key list could have changed.
    println!("cargo:rerun-if-changed={SOURCE}");

    let yaml = fs::read_to_string(SOURCE).unwrap_or_else(|e| panic!("cannot read {SOURCE}: {e}"));

    let mut out = String::from(
        "// Generated by build.rs from lib/I18n/translations/english.yaml.\n\
         //\n\
         // Look strings up with `tr!` rather than using these directly; a key\n\
         // that does not exist here is a compile error.\n\n\
         use core::ffi::CStr;\n\n",
    );

    let mut count = 0;
    for line in yaml.lines() {
        // Keys are top-level and unindented; nested metadata is not a key.
        let Some(key) = line.split(':').next() else {
            continue;
        };
        if !key.starts_with("STR_")
            || !key
                .bytes()
                .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_')
        {
            continue;
        }
        out.push_str(&format!("pub const {key}: &CStr = c\"{key}\";\n"));
        count += 1;
    }

    assert!(count > 0, "no STR_* keys found in {SOURCE}");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("strings.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}
